### ISSUE TITLE
How can I use it in my dataset?

### ISSUE THREAD

**Issue by Leozyc-waseda** [CVMI-Lab/ST3D#35]
@jihanyang 
Thanks for your awesome work.
How can I use it in my dataset.
Do you have any suggestions? Thanks a lot. :)

**Comment by jihanyang** [comment]
Hello, 
Acutally, if you already implemented the dataset in OpenPCDet, you only need to modify it to support three features:
1. Shifting coordinates  such as 
https://github.com/CVMI-Lab/ST3D/blob/812b64491c3a67a1b578fe46c375fcd0ed2c4305/pcdet/datasets/kitti/kitti_dataset.py#L279
https://github.com/CVMI-Lab/ST3D/blob/812b64491c3a67a1b578fe46c375fcd0ed2c4305/pcdet/datasets/kitti/kitti_dataset.py#L386
2. Using pseudo label, such as
https://github.com/CVMI-Lab/ST3D/blob/812b64491c3a67a1b578fe46c375fcd0ed2c4305/pcdet/datasets/kitti/kitti_dataset.py#L412
3. Evaluation and cfg:
    Such as class mapping 
    https://github.com/CVMI-Lab/ST3D/blob/812b64491c3a67a1b578fe46c375fcd0ed2c4305/tools/cfgs/da-waymo-kitti_models/secondiou/secondiou_old_anchor.yaml#L12

**Comment by laiyingxin2** [comment]
How does it work in other datasets

**Comment by Leozyc-waseda** [comment]
@jihanyang 
Does it matter if my dataset doesn't have any Ground truth?

If you can write a pipeline about how to using custom dataset, more people will discover this very advanced algorithm. 👍

**Comment by jihanyang** [comment]
It can train when your dataset doesn't have any gts. However, you need to have some gts for evaluation, otherwise I think you cannot verify its effectiveness. Actually, such guidance is in our planing, also for OpenPCDet. @Leozyc-waseda

**Comment by jihanyang** [comment]
@laiyingxin2 
By changing the target domain or source domain to any other datasets with custom dataset class.

**Comment by Leozyc-waseda** [comment]
@jihanyang 
Thank you for your reply~

>  Actually, such guidance is in our planing, also for OpenPCDet.
That's really awesome. Can you tell me about when this guidance will be released? :)

**Comment by jihanyang** [comment]
Not yet. If you are urgently needed,  maybe you can try by yourself and post your problem here. I will try my best to help you.

**Comment by Leozyc-waseda** [comment]
Thanks a lot. :)

I would like to ask if I want to use pvrcnntrain **nuscense** to **kitti** dataset.

1. I need to advance use pvrcnn Trained on nuscense.
 ```python train.py --cfg_file ${CONFIG_FILE}```

2.Then pretrain the model trained on nuscense.
Is it in this order?
first,
```
bash scripts/dist_train.sh ${NUM_GPUS} --cfg_file cfgs/da-waymo-kitti_models/secondiou_st3d/secondiou_st3d.yaml \
    --batch_size ${BATCH_SIZE} --pretrained_model ${PRETRAINED_MODEL}
```
second, self-training Process
```
bash scripts/dist_train.sh ${NUM_GPUS} --cfg_file cfgs/da-waymo-kitti_models/secondiou_st3d/secondiou_st3d.yaml \
    --batch_size ${BATCH_SIZE} --pretrained_model ${PRETRAINED_MODEL}
```

**Comment by Leozyc-waseda** [comment]
If it is correct, if I want to use the pv-rcnn model, pandaset to kitti.
I need to prepare :

1. Dataloader of pandaset, dataloader of kitti, import data
2. Prepare the pvrcnn_st3d.yaml file in **da-pandaset-kitti_models**.   and pandaset pvrcnn.yaml.
Could you please tell me what the specific changes are?
3. Train pvrcnn on pandaset
4. Pretrain or self-training process pvrcnn trained on pandaset.

is this correct？

**Comment by jihanyang** [comment]
Yes. About the 2nd point, please refer to my reply here.

> Hello, Acutally, if you already implemented the dataset in OpenPCDet, you only need to modify it to support three features:
> 
> 1. Shifting coordinates  such as
>    https://github.com/CVMI-Lab/ST3D/blob/812b64491c3a67a1b578fe46c375fcd0ed2c4305/pcdet/datasets/kitti/kitti_dataset.py#L279
>    
>    https://github.com/CVMI-Lab/ST3D/blob/812b64491c3a67a1b578fe46c375fcd0ed2c4305/pcdet/datasets/kitti/kitti_dataset.py#L386
> 2. Using pseudo label, such as
>    https://github.com/CVMI-Lab/ST3D/blob/812b64491c3a67a1b578fe46c375fcd0ed2c4305/pcdet/datasets/kitti/kitti_dataset.py#L412
> 3. Evaluation and cfg:
>    Such as class mapping
>    https://github.com/CVMI-Lab/ST3D/blob/812b64491c3a67a1b578fe46c375fcd0ed2c4305/tools/cfgs/da-waymo-kitti_models/secondiou/secondiou_old_anchor.yaml#L12

**Comment by Leozyc-waseda** [comment]
Hi @jihanyang 
I tring to use PV-RCNN pre-train on pandaset with ROS, as you mentioned in paper. 

> pre-train the object detector with ROS

But I got this error

```
[2022-04-11 03:15:12,942  train.py 168  INFO]  **********************Start training da-pandaset-kitti_models/pvrcnn/pvrcnn_old_anchor_ros(default)**********************
epochs:   0%|                                                                               | 0/50 [00:20<?, ?it/s]
Traceback (most recent call last):                                                        | 0/4880 [00:00<?, ?it/s]
  File "train.py", line 199, in <module>
    main()
  File "train.py", line 191, in main
    ema_model=None
  File "/home/algo-4/work/ST3D/tools/train_utils/train_utils.py", line 108, in train_model
    dataloader_iter=dataloader_iter
  File "/home/algo-4/work/ST3D/tools/train_utils/train_utils.py", line 34, in train_one_epoch
    batch = next(dataloader_iter)
  File "/home/algo-4/anaconda3/envs/ST3D/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 819, in __next__
    return self._process_data(data)
  File "/home/algo-4/anaconda3/envs/ST3D/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 846, in _process_data
    data.reraise()
  File "/home/algo-4/anaconda3/envs/ST3D/lib/python3.7/site-packages/torch/_utils.py", line 369, in reraise
    raise self.exc_type(msg)
AttributeError: Caught AttributeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/algo-4/anaconda3/envs/ST3D/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/algo-4/anaconda3/envs/ST3D/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/algo-4/anaconda3/envs/ST3D/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/algo-4/work/ST3D/tools/../pcdet/datasets/pandaset/pandaset_dataset.py", line 118, in __getitem__
    boxes, labels, zrot_world_to_ego = self._get_annotations(info, pose)
  File "/home/algo-4/work/ST3D/tools/../pcdet/datasets/pandaset/pandaset_dataset.py", line 211, in _get_annotations
    for lab in labels] )
  File "/home/algo-4/work/ST3D/tools/../pcdet/datasets/pandaset/pandaset_dataset.py", line 211, in <listcomp>
    for lab in labels] )
AttributeError: 'EasyDict' object has no attribute 'TRAINING_CATEGORIES'

                                                                                                                  Traceback (most recent call last):                                                                                  
  File "/home/algo-4/anaconda3/envs/ST3D/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/algo-4/anaconda3/envs/ST3D/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/algo-4/anaconda3/envs/ST3D/lib/python3.7/site-packages/torch/distributed/launch.py", line 246, in <module>
    main()
  File "/home/algo-4/anaconda3/envs/ST3D/lib/python3.7/site-packages/torch/distributed/launch.py", line 242, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/algo-4/anaconda3/envs/ST3D/bin/python', '-u', 'train.py', '--local_rank=0', '--launcher', 'pytorch', '--cfg_file', 'cfgs/da-pandaset-kitti_models/pvrcnn/pvrcnn_old_anchor_ros.yaml', '--batch_size', '1']' returned non-zero exit status 1.
```

I can train pandaset with this, so i think pandaet`s dataloader is ok.
`~/work/ST3D/tools$ python train.py --cfg_file cfgs/pandaset_models/pv_rcnn.yaml  --batch_size 1`

Here are my configuration
1. pvrcnn_old_anchor_ros.yaml

```
CLASS_NAMES: ['Car']

DATA_CONFIG:
    _BASE_CONFIG_: cfgs/dataset_configs/da_pandaset_kitti_dataset.yaml
    MAX_SWEEPS: 1
    PRED_VELOCITY: False
    BALANCED_RESAMPLING: False
    SHIFT_COOR: [0.0, 0.0, 1.8]

    DATA_AUGMENTOR:
        DISABLE_AUG_LIST: ['normalize_object_size']
        AUG_CONFIG_LIST:
            - NAME: random_object_scaling
              SCALE_UNIFORM_NOISE: [0.75, 1.0]

            - NAME: normalize_object_size
              SIZE_RES: [-0.75, -0.34, -0.2]

            - NAME: random_world_flip
              ALONG_AXIS_LIST: ['x', 'y']

            - NAME: random_world_rotation
              WORLD_ROT_ANGLE:  [-3.14159265, 3.114159265]

            - NAME: random_world_scaling
              WORLD_SCALE_RANGE: [0.95, 1.05]

DATA_CONFIG_TAR:
    _BASE_CONFIG_: cfgs/dataset_configs/da_kitti_dataset.yaml
    TARGET: True
    FOV_POINTS_ONLY: False
    CLASS_NAMES: ['Car']
    SHIFT_COOR: [0.0, 0.0, 1.6]

MODEL:
    NAME: PVRCNN

    VFE:
        NAME: MeanVFE

    BACKBONE_3D:
        NAME: VoxelBackBone8x

    MAP_TO_BEV:
        NAME: HeightCompression
        NUM_BEV_FEATURES: 256

    BACKBONE_2D:
        NAME: BaseBEVBackbone

        LAYER_NUMS: [5, 5]
        LAYER_STRIDES: [1, 2]
        NUM_FILTERS: [128, 256]
        UPSAMPLE_STRIDES: [1, 2]
        NUM_UPSAMPLE_FILTERS: [256, 256]

    DENSE_HEAD:
        NAME: AnchorHeadSingle
        CLASS_AGNOSTIC: False

        USE_DIRECTION_CLASSIFIER: True
        DIR_OFFSET: 0.78539
        DIR_LIMIT_OFFSET: 0.0
        NUM_DIR_BINS: 2

        ANCHOR_GENERATOR_CONFIG: [
            {
                'class_name': 'car',
                'anchor_sizes': [[4.2, 2.0, 1.6]],
                'anchor_rotations': [0, 1.57],
                'anchor_bottom_heights': [0],
                'align_center': False,
                'feature_map_stride': 8,
                'matched_threshold': 0.55,
                'unmatched_threshold': 0.4
            }
        ]

        TARGET_ASSIGNER_CONFIG:
            NAME: AxisAlignedTargetAssigner
            POS_FRACTION: -1.0
            SAMPLE_SIZE: 512
            NORM_BY_NUM_EXAMPLES: False
            MATCH_HEIGHT: False
            BOX_CODER: ResidualCoder

        LOSS_CONFIG:
            LOSS_WEIGHTS: {
                'cls_weight': 1.0,
                'loc_weight': 2.0,
                'dir_weight': 0.2,
                'code_weights': [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
            }

    PFE:
        NAME: VoxelSetAbstraction
        POINT_SOURCE: raw_points
        NUM_KEYPOINTS: 4096
        NUM_OUTPUT_FEATURES: 128
        SAMPLE_METHOD: FPS

        FEATURES_SOURCE: ['bev', 'x_conv3', 'x_conv4', 'raw_points']
        SA_LAYER:
            raw_points:
                MLPS: [[16, 16], [16, 16]]
                POOL_RADIUS: [0.4, 0.8]
                NSAMPLE: [16, 16]
            x_conv1:
                DOWNSAMPLE_FACTOR: 1
                MLPS: [[16, 16], [16, 16]]
                POOL_RADIUS: [0.4, 0.8]
                NSAMPLE: [16, 16]
            x_conv2:
                DOWNSAMPLE_FACTOR: 2
                MLPS: [[32, 32], [32, 32]]
                POOL_RADIUS: [0.8, 1.2]
                NSAMPLE: [16, 32]
            x_conv3:
                DOWNSAMPLE_FACTOR: 4
                MLPS: [[64, 64], [64, 64]]
                POOL_RADIUS: [1.2, 2.4]
                NSAMPLE: [16, 32]
            x_conv4:
                DOWNSAMPLE_FACTOR: 8
                MLPS: [[64, 64], [64, 64]]
                POOL_RADIUS: [2.4, 4.8]
                NSAMPLE: [16, 32]

    POINT_HEAD:
        NAME: PointHeadSimple
        CLS_FC: [256, 256]
        CLASS_AGNOSTIC: True
        USE_POINT_FEATURES_BEFORE_FUSION: True
        TARGET_CONFIG:
            GT_EXTRA_WIDTH: [0.2, 0.2, 0.2]
        LOSS_CONFIG:
            LOSS_REG: smooth-l1
            LOSS_WEIGHTS: {
                'point_cls_weight': 1.0,
            }

    ROI_HEAD:
        NAME: PVRCNNHead
        CLASS_AGNOSTIC: True

        SHARED_FC: [256, 256]
        CLS_FC: [256, 256]
        REG_FC: [256, 256]
        DP_RATIO: 0.3

        NMS_CONFIG:
            TRAIN:
                NMS_TYPE: nms_gpu
                MULTI_CLASSES_NMS: False
                NMS_PRE_MAXSIZE: 9000
                NMS_POST_MAXSIZE: 512
                NMS_THRESH: 0.8
            TEST:
                NMS_TYPE: nms_gpu
                MULTI_CLASSES_NMS: False
                NMS_PRE_MAXSIZE: 1024
                NMS_POST_MAXSIZE: 100
                NMS_THRESH: 0.7

        ROI_GRID_POOL:
            GRID_SIZE: 6
            MLPS: [[64, 64], [64, 64]]
            POOL_RADIUS: [0.8, 1.6]
            NSAMPLE: [16, 16]
            POOL_METHOD: max_pool

        TARGET_CONFIG:
            BOX_CODER: ResidualCoder
            ROI_PER_IMAGE: 128
            FG_RATIO: 0.5

            SAMPLE_ROI_BY_EACH_CLASS: True
            CLS_SCORE_TYPE: raw_roi_iou

            CLS_FG_THRESH: 0.75
            CLS_BG_THRESH: 0.25
            CLS_BG_THRESH_LO: 0.1
            HARD_BG_RATIO: 0.8

            REG_FG_THRESH: 0.55

        LOSS_CONFIG:
            CLS_LOSS: BinaryCrossEntropy
            REG_LOSS: smooth-l1
            CORNER_LOSS_REGULARIZATION: True
            LOSS_WEIGHTS: {
                'rcnn_cls_weight': 1.0,
                'rcnn_reg_weight': 1.0,
                'rcnn_corner_weight': 1.0,
                'code_weights': [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
            }

    POST_PROCESSING:
        RECALL_THRESH_LIST: [0.3, 0.5, 0.7]
        SCORE_THRESH: 0.1
        OUTPUT_RAW_SCORE: False

        EVAL_METRIC: kitti

        NMS_CONFIG:
            MULTI_CLASSES_NMS: False
            NMS_TYPE: nms_gpu
            NMS_THRESH: 0.1
            NMS_PRE_MAXSIZE: 4096
            NMS_POST_MAXSIZE: 500


OPTIMIZATION:
    NUM_EPOCHS: 50
    BATCH_SIZE_PER_GPU: 2
    OPTIMIZER: adam_onecycle
    LR: 0.01
    WEIGHT_DECAY: 0.001
    MOMENTUM: 0.9

    MOMS: [0.95, 0.85]
    PCT_START: 0.4
    DIV_FACTOR: 10
    DECAY_STEP_LIST: [35, 45]
    LR_DECAY: 0.1
    LR_CLIP: 0.0000001

    LR_WARMUP: False
    WARMUP_EPOCH: 1

    GRAD_NORM_CLIP: 10
```

2. da_pandaset_kitti_dataset.yaml

```
DATASET: 'PandasetDataset'
DATA_PATH: '../data/pandaset'

POINT_CLOUD_RANGE: [-70, -40, -3, 70, 40, 1] # xmin, ymin, zmin, xmax, ymax, zmax
#[-70, -70, -2.052, 70, 70, 0.348] # xmin, ymin, zmin, xmax, ymax, zmax

DATA_SPLIT: {
    'train': train,
    'test': val
}

SEQUENCES: {
    'train': ['014', '050', '079', '048', '093', '091', '063', '104', '100', '092', '012', '047', '018', '006', '099', '085', '035', '041', '052', '105', '030', '113', '002', '084', '028', '119', '044', '005', '102', '034', '077', '064', '067', '058', '019', '015', '037', '095', '120', '066', '023', '071', '117', '098', '139', '038', '116', '046', '088', '089', '040', '033', '016', '024', '122', '039', '158', '069', '124', '123', '106'], # ~60% of the sequences, randomly chosen
    'val': ['045', '059', '055', '051', '020', '097', '073', '043', '003', '101', '027', '056', '011', '078', '080', '109', '042', '021', '094', '057'], # ~20% of the sequences, randomly chosen
    'test': ['074', '004', '086', '062', '068', '008', '001', '110', '053', '115', '054', '065', '017', '103', '072', '013', '029', '090', '112', '149', '070', '032'] # ~20% of the sequences, randomly chosen
}

LIDAR_DEVICE: 0


INFO_PATH: {
    'train': [pandaset_infos_train.pkl],
    'test': [pandaset_infos_val.pkl],
}

MIN_POINTS_OF_GT: 1

DATA_AUGMENTOR:
    DISABLE_AUG_LIST: ['random_object_scaling', 'normalize_object_size']
    AUG_CONFIG_LIST:
        - NAME: random_object_scaling
          SCALE_UNIFORM_NOISE: [0.75, 1.0]

        - NAME: normalize_object_size
          SIZE_RES: [-0.75, -0.34, -0.2]

        - NAME: random_world_flip
          ALONG_AXIS_LIST: ['x', 'y']

        - NAME: random_world_rotation
          WORLD_ROT_ANGLE: [-3.14159265, 3.114159265]

        - NAME: random_world_scaling
          WORLD_SCALE_RANGE: [0.95, 1.05]


POINT_FEATURE_ENCODING: {
    encoding_type: absolute_coordinates_encoding,
    used_feature_list: ['x', 'y', 'z'],
    src_feature_list: ['x', 'y', 'z', 'intensity'],
}


DATA_PROCESSOR:
    - NAME: mask_points_and_boxes_outside_range
      REMOVE_OUTSIDE_BOXES: True

    - NAME: shuffle_points
      SHUFFLE_ENABLED: {
        'train': True,
        'test': False
      }

    - NAME: transform_points_to_voxels
      VOXEL_SIZE: [0.05, 0.05, 0.1]
      MAX_POINTS_PER_VOXEL: 5
      MAX_NUMBER_OF_VOXELS: {
        'train': 80000,
        'test': 90000
      }

```

Any sugguestions? :(
