### ISSUE TITLE
Have you ever tried ST3D on PointPillars?

### ISSUE THREAD

**Issue by MaxDumbledore** [CVMI-Lab/ST3D#74]
I am trying to add another roi head to predict iou for pointpillars(just like second-iou). But when I do pretraining, I found that the performance is bad. Do you have any suggestions for changing the pointpillars structure?

Here is part of my config file.

```
  BACKBONE_2D:
    NAME: BaseBEVBackbone
    LAYER_NUMS: [3, 5, 5]
    LAYER_STRIDES: [2, 2, 2]
    NUM_FILTERS: [64, 128, 256]
    UPSAMPLE_STRIDES: [1, 2, 4]
    NUM_UPSAMPLE_FILTERS: [128, 128, 128]  # #torch.Size([1, 128*3, H, W])
```

and
```
  ROI_HEAD:
    NAME: SECONDHead
    CLASS_AGNOSTIC: True

    SHARED_FC: [256, 256]
    IOU_FC: [256, 256]
    DP_RATIO: 0.3

    NMS_CONFIG:
      TRAIN:
        NMS_TYPE: nms_gpu
        MULTI_CLASSES_NMS: False
        NMS_PRE_MAXSIZE: 9000
        NMS_POST_MAXSIZE: 512
        NMS_THRESH: 0.8
      TEST:
        NMS_TYPE: nms_gpu
        MULTI_CLASSES_NMS: False
        NMS_PRE_MAXSIZE: 1024
        NMS_POST_MAXSIZE: 100
        NMS_THRESH: 0.7

    ROI_GRID_POOL:
      GRID_SIZE: 7
      IN_CHANNEL: 384
      DOWNSAMPLE_RATIO: 8
      ...
```
